#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.15

pipelines:
  default:
    - parallel:
      - step:
          name: Test and Build
          script:
            #- mkdir test-reports
            #- go get -u bitbucket.org/yellowmessenger/asterisk-ari
            #- go test tests/* -v 2>&1 | go-junit-report > test-reports/report.xml
            # Build compiles the packages
            #- cd utils/grpc/proto && protoc --go_out=plugins=grpc:. *.proto && cd ../../../
            - env GOOS=linux go build -o asterisk-ari
      - step:
          name: Deploy to test
          deployment: test
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - echo "Deploying to test environment"
