// Code generated by "stringer -type=CallDirection -linecomment"; DO NOT EDIT.

package call

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirectionInbound-1]
	_ = x[DirectionOutbound-2]
}

const _CallDirection_name = "inboundoutbound"

var _CallDirection_index = [...]uint8{0, 7, 15}

func (i CallDirection) String() string {
	i -= 1
	if i < 0 || i >= CallDirection(len(_CallDirection_index)-1) {
		return "CallDirection(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CallDirection_name[_CallDirection_index[i]:_CallDirection_index[i+1]]
}
