// Code generated by "stringer -type=PipeType -trimprefix=PipeType"; DO NOT EDIT.

package call

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PipeTypeSIP-1]
	_ = x[PipeTypePRI-2]
}

const _PipeType_name = "SIPPRI"

var _PipeType_index = [...]uint8{0, 3, 6}

func (i PipeType) String() string {
	i -= 1
	if i < 0 || i >= PipeType(len(_PipeType_index)-1) {
		return "PipeType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PipeType_name[_PipeType_index[i]:_PipeType_index[i+1]]
}
