// Code generated by "stringer -type=Status -linecomment"; DO NOT EDIT.

package call

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusInitiated-1]
	_ = x[StatusAnswered-2]
	_ = x[StatusNotAnswered-3]
	_ = x[StatusFailed-4]
	_ = x[StatusNotValid-5]
	_ = x[StatusUnknown-6]
}

const _Status_name = "initiatedanswerednot_answeredfailednot_validunknown"

var _Status_index = [...]uint8{0, 9, 17, 29, 35, 44, 51}

func (i Status) String() string {
	i -= 1
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
