// Code generated by "stringer -type=State -trimprefix=State"; DO NOT EDIT.

package call

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateDialing-1]
	_ = x[StateRinging-2]
	_ = x[StateUp-3]
}

const _State_name = "DialingRingingUp"

var _State_index = [...]uint8{0, 7, 14, 16}

func (i State) String() string {
	i -= 1
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
